"""empty message

Revision ID: 49946ac1a13b
Revises: dbbd71c29b92
Create Date: 2025-03-06 14:25:51.923538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49946ac1a13b'
down_revision = 'dbbd71c29b92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shelter_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_shelter_id_shelters'), 'shelters', ['shelter_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_shelter_id_shelters'), type_='foreignkey')
        batch_op.drop_column('shelter_id')

    # ### end Alembic commands ###
