"""fix circular users shelters

Revision ID: 67dab6d5e400
Revises: cff45485aebd
Create Date: 2025-03-05 17:36:39.355142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67dab6d5e400'
down_revision = 'cff45485aebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owned_shelter_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_owned_shelter_id_shelters'), 'shelters', ['owned_shelter_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_owned_shelter_id_shelters'), type_='foreignkey')
        batch_op.drop_column('owned_shelter_id')

    # ### end Alembic commands ###
