"""empty message

Revision ID: 85a8c1e452d7
Revises: a5366f423287
Create Date: 2025-03-06 16:35:14.885549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a8c1e452d7'
down_revision = 'a5366f423287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shelter_workers')
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('rescue_info')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(length=1000), nullable=False))
        batch_op.add_column(sa.Column('date_sent', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('fk_messages_animal_id_animals', type_='foreignkey')
        batch_op.drop_column('content')
        batch_op.drop_column('created_at')
        batch_op.drop_column('animal_id')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('shelters', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('shelters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('animal_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=False))
        batch_op.create_foreign_key('fk_messages_animal_id_animals', 'animals', ['animal_id'], ['id'])
        batch_op.drop_column('date_sent')
        batch_op.drop_column('message')

    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('rescue_info', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    op.create_table('shelter_workers',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('shelter_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['shelter_id'], ['shelters.id'], name='fk_shelter_workers_shelter_id_shelters'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_shelter_workers_user_id_users'),
    sa.PrimaryKeyConstraint('user_id', 'shelter_id')
    )
    # ### end Alembic commands ###
