"""empty message

Revision ID: 9b2c73904a7f
Revises: 066250e39f15
Create Date: 2025-03-06 20:08:12.554651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b2c73904a7f'
down_revision = '066250e39f15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shelters', schema=None) as batch_op:
        batch_op.drop_constraint('fk_shelters_worker_id_users', type_='foreignkey')
        batch_op.drop_column('worker_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shelter_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_shelter_id_shelters'), 'shelters', ['shelter_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_shelter_id_shelters'), type_='foreignkey')
        batch_op.drop_column('shelter_id')

    with op.batch_alter_table('shelters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_shelters_worker_id_users', 'users', ['worker_id'], ['id'])

    # ### end Alembic commands ###
