"""empty message

Revision ID: a5366f423287
Revises: 49946ac1a13b
Create Date: 2025-03-06 16:23:12.249275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5366f423287'
down_revision = '49946ac1a13b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelter_workers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shelter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shelter_id'], ['shelters.id'], name=op.f('fk_shelter_workers_shelter_id_shelters')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_shelter_workers_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'shelter_id')
    )
    with op.batch_alter_table('shelters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_shelters_owner_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_shelters_worker_id_users'), 'users', ['worker_id'], ['id'])
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_shelter_id_shelters', type_='foreignkey')
        batch_op.drop_column('shelter_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shelter_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_users_shelter_id_shelters', 'shelters', ['shelter_id'], ['id'])

    with op.batch_alter_table('shelters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_shelters_worker_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_shelters_owner_id_users', 'users', ['owner_id'], ['id'])
        batch_op.drop_column('worker_id')

    op.drop_table('shelter_workers')
    # ### end Alembic commands ###
