"""updated models

Revision ID: cff45485aebd
Revises: 46fdf75ceb75
Create Date: 2025-03-05 17:25:01.809690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff45485aebd'
down_revision = '46fdf75ceb75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rescue_date', sa.DateTime(), nullable=False),
    sa.Column('rescue_info', sa.String(length=500), nullable=True),
    sa.Column('species', sa.String(length=100), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.Enum(), nullable=False),
    sa.Column('weight', sa.String(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('special_needs', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum(), nullable=False),
    sa.Column('shelter_id', sa.Integer(), nullable=True),
    sa.Column('foster_id', sa.Integer(), nullable=True),
    sa.Column('transport_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['foster_id'], ['users.id'], name=op.f('fk_animals_foster_id_users')),
    sa.ForeignKeyConstraint(['shelter_id'], ['shelters.id'], name=op.f('fk_animals_shelter_id_shelters')),
    sa.ForeignKeyConstraint(['transport_id'], ['users.id'], name=op.f('fk_animals_transport_id_users')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('medical_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('diagnosis', sa.String(length=500), nullable=False),
    sa.Column('treatment', sa.String(length=500), nullable=True),
    sa.Column('allergies', sa.String(), nullable=True),
    sa.Column('existing_conditions', sa.String(length=1000), nullable=True),
    sa.Column('rabies_shot', sa.Boolean(), nullable=True),
    sa.Column('rabies_date', sa.DateTime(), nullable=True),
    sa.Column('snap_shot', sa.Boolean(), nullable=True),
    sa.Column('snap_date', sa.DateTime(), nullable=True),
    sa.Column('dhpp_shot', sa.Boolean(), nullable=True),
    sa.Column('dhpp_date', sa.DateTime(), nullable=True),
    sa.Column('date_of_record', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], name=op.f('fk_medical_records_animal_id_animals')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], name=op.f('fk_messages_animal_id_animals')),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name=op.f('fk_messages_recipient_id_users')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_messages_sender_id_users')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('medical_records')
    op.drop_table('animals')
    # ### end Alembic commands ###
