"""empty message

Revision ID: dbbd71c29b92
Revises: 461a64b194a6
Create Date: 2025-03-06 10:17:20.276893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbbd71c29b92'
down_revision = '461a64b194a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_shelter_id_shelters', type_='foreignkey')
        batch_op.drop_column('shelter_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shelter_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_users_shelter_id_shelters', 'shelters', ['shelter_id'], ['id'])

    # ### end Alembic commands ###
